<?php
/**
 * Created by PhpStorm.
 * User: JHR
 * Date: 2019/6/25
 * Time: 21:29
 */
namespace app\admin\controller;
use think\Db;
require_once ROOT_PATH . '/extend/qiniu/autoload.php';
use Qiniu\Auth;
use Qiniu\Config;
use Qiniu\Storage\BucketManager;
class Qiniu extends Base {
    protected $accessKey;
    protected $secretKey;
    protected $bucket;
    protected $domain;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->accessKey = config('qiniu_ak');
        $this->secretKey = config('qiniu_sk');
        $this->bucket = config('qiniu_bucket');
        $this->domain = config('qiniu_domain');
    }
    // 生成上传Token
    public function getUpToken() {
        $auth = new Auth($this->accessKey, $this->secretKey);
        $suffix = input('post.suffix');
        $fkey = create_unique_number('');
        $filename = 'tmp/' . $fkey . $suffix;
        $callbackBody = [
            'fname' => $filename,
            'fkey' => $fkey,
            'desc' => '文件描述'
        ];
        $policy = [
            'callbackUrl' => $_SERVER['REQUEST_SCHEME'] . '://'.$_SERVER['HTTP_HOST'].'/qiniu_callback.php',
            'callbackBody' => json_encode($callbackBody)
        ];
        $token = $auth->uploadToken($this->bucket,null,3600,$policy);
        $data = [
            'token' => $token,
            'domain' => $this->domain,
            'filename' => $filename
        ];
        return ajax($data);
    }


}