<?php
/**
 * Created by PhpStorm.
 * User: JHR
 * Date: 2019/7/11
 * Time: 17:12
 */
namespace app\api\controller;

use think\Controller;
use think\Db;
class Plan extends Controller {

    private $cmd = '';

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->cmd = request()->module() . '/' . request()->controller() . '/' . request()->action();
    }

    public function test() {
        $arr = [];
        try {
            echo $arr['name'];
        } catch (\Exception $e) {
            echo 'catch result: ';
            die($e->getMessage());
        }
//        $this->planlog($this->cmd,var_export($_SERVER['REMOTE_ADDR'],true));
//        halt($_SERVER);
    }



    protected function planlog($cmd,$str) {
        $file= ROOT_PATH . '/plan.log';
        $text='[Time ' . date('Y-m-d H:i:s') ."]\ncmd:" .$cmd. "\n" .$str. "\n---END---" . "\n";
        if(false !== fopen($file,'a+')){
            file_put_contents($file,$text,FILE_APPEND);
        }else{
            echo '创建失败';
        }
    }


}